feat: added redirect load
heitorlimamorei/gpt-solver pull request #17
Opened 2024-04-12 22:07 UTC by felipeRese

### Tipo de alteração

- [ ] Correção de bug 
- [x] Novo recurso 
- [ ] Alteração de funcionalidade/recurso
- [ ] Mudanças visuais (apenas css modificado)
- [ ] Mudanças de CI/CD

2024-04-13 01:36 UTC, heitorlimamorei requested changes
Por favor, olhe os comentarios que fiz no conversation. Problemas lógicos graves.

2024-04-13 01:36 UTC, heitorlimamorei commented on src/components/chat/ChatMessage.tsx
> +              ? Logo
Você deve adcionar a Profile imagem da mesma forma que vc adicionou a logo, fazendo o import e adicionando a varaiavel importada como src. Da forma como está ai, está ocorrendo erro.

2024-04-13 01:36 UTC, heitorlimamorei commented on src/app/page.tsx
> +
Não pode usar router no App Dir do next 14+. Usar push refs na url para fazer o redirect.

2024-04-13 01:36 UTC, heitorlimamorei commented on src/app/page.tsx
> +          if (result.data?.chats?.length > 0) {
Esse código não faz sentido, pois estamos querendo lidar com o cenáio em que está demorando para obter o array de chat ids. O timeout está sendo instanciado somente após ter os chats disponiveis, o que não faz sentido algum.

2024-04-13 01:38 UTC, heitorlimamorei commented on src/app/page.tsx
> +          if (result.data?.chats?.length > 0) {
Além disso, tomar cuidado com estados desnecessarios. Na abordagem que você subiu esse userData ficou inutilizado, entretanto, não foi deletado.

2024-04-14 03:18 UTC, felipeRese commented on src/app/page.tsx
> +
Nesse caso eu estou utilizando o router que vem do 'next/navigation', que funciona do App Dir.

2024-04-14 03:18 UTC, felipeRese commented on src/app/page.tsx
> +          if (result.data?.chats?.length > 0) {
Nisso que da confiar demais no gpt. Mas acho que consegui outra solucao.

2024-04-14 18:19 UTC, heitorlimamorei commented on src/app/page.tsx
> +          if (result.data?.chats?.length > 0) {
O código fez mais sentido, mas acho que ainda não está resolvendo em 100%.

2024-05-01 18:40 UTC, merged